management:
  endpoint:
    health:
      show-details: always

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/referential
    username: admin
    password: admin

logging:
  level:
    org.springframework.r2dbc: DEBUG