version: '3'

services:
  app:
    image: 'api'
    build:
      context: ../../
      dockerfile: ./.docker/project/Dockerfile
    container_name: artist-app
    networks:
      - artist-api-net
    ports:
      - 8080:8080
    depends_on:
      - liquibase
    environment:
      - spring.r2dbc.url=r2dbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - spring.r2dbc.username=${POSTGRES_USER}
      - spring.r2dbc.password=${POSTGRES_PASSWORD}
      - logging.level.org.springframework.r2dbc=DEBUG
  liquibase:
    image: liquibase/liquibase
    container_name: liquibase-migration
    networks:
      - artist-api-net
    depends_on:
      - db
    command: --log-level=INFO --url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD} --changeLogFile=workspace/changelog-root.xml update
    volumes:
      - ../../src/main/resources/db/changelogs/:/liquibase/workspace

  adminer:
    image: adminer
    restart: always
    networks:
      - artist-api-net
    depends_on:
      - db
    ports:
      - 8090:8080

  db:
    image: postgres:latest
    networks:
      - artist-api-net
    command: -p ${POSTGRES_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
networks:
  artist-api-net: